### PR TITLE
Auto updater

### PR DESCRIPTION
**Pull request by MoritzWM**
I wrote a very simple auto-updating function that just re-installs straight from GitHub:
`tomotools update <--branch main>`

I think this would be very useful for people that don't want an editable installation and mess with git commands all the time.
I think though we should then also write proper installation instructions, including how to make a conda/virtualenv environment.

### CODE REVIEW

**Comment by MoritzWM** [comment]
Small additional thing: the shell.nix file is for development on NixOS, which is what I'm working on. No need to worry about it.

**Comment by MoritzWM** [comment]
@bwmr Please also try the installation and auto-updating. You will have to specifically ask for the auto_updater branch during installation and updating. Right now, it works on my machine, but that doesn't mean much I guess.

**Comment by bwmr** [comment]
Tested on macOS, waiting for IT to update CA Bundle on CentOS to check there also.

**Comment by MoritzWM** [comment]
Does .sbgrid.conf support comments? Then we could also put that config into a code-block

**Comment by bwmr** [comment]
Tested on CentOS also, certificate problem was on my side.

**Pull request merged**
